"""init

Revision ID: 003dae0d041c
Revises: 
Create Date: 2026-02-02 14:13:05.627670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '003dae0d041c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('primary_color', sa.String(length=20), nullable=True),
    sa.Column('secondary_color', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('payment_webhook_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('external_event_id', sa.String(length=120), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webhook_brand_provider', 'payment_webhook_events', ['brand_id', 'provider'], unique=False)
    op.create_index('ix_webhook_event_type', 'payment_webhook_events', ['event_type'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('external_product_id', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_plans_brand', 'plans', ['brand_id'], unique=False)
    op.create_table('workout_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workout_templates_brand', 'workout_templates', ['brand_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('user', 'pro', 'admin', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('challenge_started_at', sa.DateTime(), nullable=True),
    sa.Column('whatsapp_ai_active_until', sa.DateTime(), nullable=True),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('subscription_status', sa.Enum('free', 'active', 'canceled', 'past_due', 'expired', name='subscriptionstatus'), nullable=False),
    sa.Column('plan_valid_until', sa.DateTime(), nullable=True),
    sa.Column('external_customer_id', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'email', name='uq_users_brand_email'),
    sa.UniqueConstraint('brand_id', 'phone', name='uq_users_brand_phone')
    )
    op.create_index('ix_users_brand', 'users', ['brand_id'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_table('workout_exercises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workout_template_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('reps', sa.String(length=50), nullable=True),
    sa.Column('load', sa.String(length=50), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.Column('youtube_url', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workout_template_id'], ['workout_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workout_exercises_template', 'workout_exercises', ['workout_template_id'], unique=False)
    op.create_table('professional_user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('professional_id', 'user_id', name='uq_prof_user_pair')
    )
    op.create_index('ix_prof_user_brand', 'professional_user', ['brand_id'], unique=False)
    op.create_index('ix_prof_user_professional', 'professional_user', ['professional_id'], unique=False)
    op.create_index('ix_prof_user_user', 'professional_user', ['user_id'], unique=False)
    op.create_table('user_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assess_brand_user', 'user_assessments', ['brand_id', 'user_id'], unique=False)
    op.create_table('user_photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('photo_type', sa.Enum('front', 'back', 'side_left', 'side_right', name='phototype'), nullable=False),
    sa.Column('url', sa.String(length=800), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_photos_brand_user', 'user_photos', ['brand_id', 'user_id'], unique=False)
    op.create_index('ix_photos_user_type', 'user_photos', ['user_id', 'photo_type'], unique=False)
    op.create_table('water_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('ml', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'log_date', name='uq_water_user_day')
    )
    op.create_index('ix_water_brand_user_date', 'water_logs', ['brand_id', 'user_id', 'log_date'], unique=False)
    op.create_table('workout_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('workout_template_id', sa.UUID(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workout_template_id'], ['workout_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'workout_template_id', 'session_date', name='uq_session_unique_day')
    )
    op.create_index('ix_sessions_brand_user_date', 'workout_sessions', ['brand_id', 'user_id', 'session_date'], unique=False)
    op.create_table('workout_session_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['workout_exercises.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'exercise_id', name='uq_session_exercise')
    )
    op.create_index('ix_session_items_session', 'workout_session_items', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_session_items_session', table_name='workout_session_items')
    op.drop_table('workout_session_items')
    op.drop_index('ix_sessions_brand_user_date', table_name='workout_sessions')
    op.drop_table('workout_sessions')
    op.drop_index('ix_water_brand_user_date', table_name='water_logs')
    op.drop_table('water_logs')
    op.drop_index('ix_photos_user_type', table_name='user_photos')
    op.drop_index('ix_photos_brand_user', table_name='user_photos')
    op.drop_table('user_photos')
    op.drop_index('ix_assess_brand_user', table_name='user_assessments')
    op.drop_table('user_assessments')
    op.drop_index('ix_prof_user_user', table_name='professional_user')
    op.drop_index('ix_prof_user_professional', table_name='professional_user')
    op.drop_index('ix_prof_user_brand', table_name='professional_user')
    op.drop_table('professional_user')
    op.drop_index('ix_workout_exercises_template', table_name='workout_exercises')
    op.drop_table('workout_exercises')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_brand', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_workout_templates_brand', table_name='workout_templates')
    op.drop_table('workout_templates')
    op.drop_index('ix_plans_brand', table_name='plans')
    op.drop_table('plans')
    op.drop_index('ix_webhook_event_type', table_name='payment_webhook_events')
    op.drop_index('ix_webhook_brand_provider', table_name='payment_webhook_events')
    op.drop_table('payment_webhook_events')
    op.drop_table('brands')
    # ### end Alembic commands ###