"""init2

Revision ID: d14c5ae60eee
Revises: 003dae0d041c
Create Date: 2026-02-04 15:06:33.126995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd14c5ae60eee'
down_revision: Union[str, Sequence[str], None] = '003dae0d041c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'brand_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_users_brand_id'), 'users', ['brand_id'], unique=False)
    op.create_unique_constraint(None, 'users', ['phone'])
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_brand_id'), table_name='users')
    op.alter_column('users', 'brand_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
